version: "3.8"

services:
  vaultwarden:
    image: vaultwarden/server:latest
    environment:
      - ADMIN_TOKEN=$$argon2id$$v=19$$m=65540,t=3,p=4$$ak00RFBPT3VjMG1pYUhFdHREOUkwbGNpYzJKbzBlSmJhZHNEckcrR3c2MD0$$cq5qUwl8+0ImM+g3DzxR1J0zC8XxDyC8JlSU4LB4be8
      - WEBSOCKET_ENABLED=false
      - SIGNUPS_ALLOWED=false
      - INVITATIONS_ALLOWED=true
      - DOMAIN=https://${DOMAIN}
    volumes:
      - vaultwarden_data_v1:/data
    networks:
      - dokploy-network
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.vaultwarden.rule=Host(`${DOMAIN}`)"
        - "traefik.http.routers.vaultwarden.entrypoints=web"
        - "traefik.http.routers.vaultwarden.tls=false"
        - "traefik.http.services.vaultwarden.loadbalancer.server.port=80"
        - "traefik.docker.network=dokploy-network"
        - "diun.enable=true"

volumes:
  vaultwarden_data_v1:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=192.168.1.184,nfsvers=4.1,rw"
      device: ":/export/appdata/vaultwarden"

networks:
  dokploy-network:
    external: true
